# Uncomment local_backend when you need to develop in your local
#local_backend: true # run npx netlify-cms-proxy-server for local testing
backend:
  name: github
  repo: miftacul/t2-edu-info
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: "static/assets"
public_folder: "/assets"

collections:
  - name: "posts" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Posts" # Used in the UI
    label_singular: "Post" # Used in the UI, ie: "New Post"
    description: >
      Create awesome content here.
    folder: "src/content/posts"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    summary: "{{title}} — {{year}}/{{month}}/{{day}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {
          label: "Template",
          name: "template",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string", tagname: "h1" }
      - {
          label: "Slug",
          name: "slug",
          widget: "string",
          hint: "Start slug with /. Use only alphanumeric characters, - and _. Avoid spaces in any cases.",
        }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          dateFormat: "YYYY-MM-DD",
          timeFormat: "HH:mm",
          format: "YYYY-MM-DD HH:mm",
        }
      - {
          label: "Tampilkan di Halaman Utama",
          name: "isMain",
          widget: "boolean",
        }
      - { label: "Tagline", name: "tagline", widget: "string" }
      - { label: "SEO Description", name: "description", widget: "string" }
      - {
          label: "Featured Image",
          name: "featuredImage",
          widget: "image",
          required: false,
          tagname: "",
        }

      - {
          label: "Body",
          name: "body",
          widget: "markdown",
          hint: "Main content goes here.",
        }
  - label: "Pages"
    name: "pages"
    files:
      - label: "About"
        name: "about"
        file: "src/content/pages/about.md"
        fields:
          - {
              label: "Template",
              name: "template",
              widget: "hidden",
              default: "about-page",
            }
          - {
              label: "Tampilkan di Halaman Utama",
              name: "isMain",
              widget: "boolean",
            }
          - { label: "Tagline", name: "tagline", widget: "string" }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Featured Image", name: "featuredImage", widget: "image" }
          - { label: "Slug", name: "slug", widget: "hidden", default: "/about" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Program"
        name: "program"
        file: "src/content/pages/program.md"
        fields:
          - {
              label: "Template",
              name: "template",
              widget: "hidden",
              default: "program-page",
            }
          - {
              label: "Tampilkan di Halaman Utama",
              name: "isMain",
              widget: "boolean",
            }
          - { label: "Tagline", name: "tagline", widget: "string" }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Featured Image", name: "featuredImage", widget: "image" }
          - {
              label: "Slug",
              name: "slug",
              widget: "hidden",
              default: "/program",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
  - name: settings
    label: Settings
    files:
      - name: general
        label: General
        file: "src/util/site.json"
        fields:
          - label: meta
            name: meta
            widget: object
            fields:
              - widget: string
                name: title
                label: Site Title
                required: true
              - widget: string
                name: titleTemplate
                label: Title Template
                default: "%s"
                required: true
              - widget: string
                name: siteUrl
                label: Website URL
                required: true
              - widget: text
                name: description
                label: Description
                default: ""
                required: false
              - widget: image
                name: image
                label: image
                default: "/assets/stackrole.png"
              - widget: string
                name: twitterUsername
                label: Twitter Username
                required: false
              - widget: string
                name: igUsername
                label: Instagram Username
                required: false
              - widget: string
                name: facebookUsername
                label: Facebook Username
                required: false
              - widget: string
                name: gmapLocationUrl
                label: Gmap Location Url
                required: false
              - widget: string
                name: phoneNumber
                label: CS Number
                required: false
              - widget: string
                name: copyright
                label: Copyright Description
                required: false
              - widget: string
                name: location
                label: Address Location
                required: false

          - label: "Google Analytics"
            name: ga
            widget: string
            hint: "Add you tracking ID, for example UA-XXXXXXXXX-X"
      - name: wa
        label: "Contact WA"
        file: "src/data/wa.json"
        fields:
          - widget: string
            name: hp
            label: Hp
            hint: "Add your WA Number. Start with 62"
          - widget: string
            name: message
            label: Message
            hint: "Add welcome message"
